# Generated by Django 3.2.8 on 2021-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='categoria',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='condicao_pagamento',
            field=models.ManyToManyField(to='main.Condicao_Pagamento'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='imagem2',
            field=models.ImageField(blank=True, upload_to='imagens'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='imagem3',
            field=models.ImageField(blank=True, upload_to='imagens'),
        ),
    ]
