# Generated by Django 3.2 on 2021-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211120_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='imagem',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
